package com.example.wataru.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.wataru.greendao.db.Object;
import com.example.wataru.greendao.db.HouseMovingCondition;
import com.example.wataru.greendao.db.ObjectImage;
import com.example.wataru.greendao.db.PreviewConfirm;
import com.example.wataru.greendao.db.PreviewConfirmDetail;

import com.example.wataru.greendao.db.ObjectDao;
import com.example.wataru.greendao.db.HouseMovingConditionDao;
import com.example.wataru.greendao.db.ObjectImageDao;
import com.example.wataru.greendao.db.PreviewConfirmDao;
import com.example.wataru.greendao.db.PreviewConfirmDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig objectDaoConfig;
    private final DaoConfig houseMovingConditionDaoConfig;
    private final DaoConfig objectImageDaoConfig;
    private final DaoConfig previewConfirmDaoConfig;
    private final DaoConfig previewConfirmDetailDaoConfig;

    private final ObjectDao objectDao;
    private final HouseMovingConditionDao houseMovingConditionDao;
    private final ObjectImageDao objectImageDao;
    private final PreviewConfirmDao previewConfirmDao;
    private final PreviewConfirmDetailDao previewConfirmDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        objectDaoConfig = daoConfigMap.get(ObjectDao.class).clone();
        objectDaoConfig.initIdentityScope(type);

        houseMovingConditionDaoConfig = daoConfigMap.get(HouseMovingConditionDao.class).clone();
        houseMovingConditionDaoConfig.initIdentityScope(type);

        objectImageDaoConfig = daoConfigMap.get(ObjectImageDao.class).clone();
        objectImageDaoConfig.initIdentityScope(type);

        previewConfirmDaoConfig = daoConfigMap.get(PreviewConfirmDao.class).clone();
        previewConfirmDaoConfig.initIdentityScope(type);

        previewConfirmDetailDaoConfig = daoConfigMap.get(PreviewConfirmDetailDao.class).clone();
        previewConfirmDetailDaoConfig.initIdentityScope(type);

        objectDao = new ObjectDao(objectDaoConfig, this);
        houseMovingConditionDao = new HouseMovingConditionDao(houseMovingConditionDaoConfig, this);
        objectImageDao = new ObjectImageDao(objectImageDaoConfig, this);
        previewConfirmDao = new PreviewConfirmDao(previewConfirmDaoConfig, this);
        previewConfirmDetailDao = new PreviewConfirmDetailDao(previewConfirmDetailDaoConfig, this);

        registerDao(Object.class, objectDao);
        registerDao(HouseMovingCondition.class, houseMovingConditionDao);
        registerDao(ObjectImage.class, objectImageDao);
        registerDao(PreviewConfirm.class, previewConfirmDao);
        registerDao(PreviewConfirmDetail.class, previewConfirmDetailDao);
    }
    
    public void clear() {
        objectDaoConfig.getIdentityScope().clear();
        houseMovingConditionDaoConfig.getIdentityScope().clear();
        objectImageDaoConfig.getIdentityScope().clear();
        previewConfirmDaoConfig.getIdentityScope().clear();
        previewConfirmDetailDaoConfig.getIdentityScope().clear();
    }

    public ObjectDao getObjectDao() {
        return objectDao;
    }

    public HouseMovingConditionDao getHouseMovingConditionDao() {
        return houseMovingConditionDao;
    }

    public ObjectImageDao getObjectImageDao() {
        return objectImageDao;
    }

    public PreviewConfirmDao getPreviewConfirmDao() {
        return previewConfirmDao;
    }

    public PreviewConfirmDetailDao getPreviewConfirmDetailDao() {
        return previewConfirmDetailDao;
    }

}
