package com.example.wataru.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOUSE_MOVING_CONDITION.
 */
public class HouseMovingCondition {

    private Long id;
    private String hmcName;
    private Boolean necessary;

    public HouseMovingCondition() {
    }

    public HouseMovingCondition(Long id) {
        this.id = id;
    }

    public HouseMovingCondition(Long id, String hmcName, Boolean necessary) {
        this.id = id;
        this.hmcName = hmcName;
        this.necessary = necessary;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHmcName() {
        return hmcName;
    }

    public void setHmcName(String hmcName) {
        this.hmcName = hmcName;
    }

    public Boolean getNecessary() {
        return necessary;
    }

    public void setNecessary(Boolean necessary) {
        this.necessary = necessary;
    }

}
