package com.example.wataru.greendao.db;

import java.util.List;
import com.example.wataru.greendao.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT.
 */
public class Object {

    private Long id;
    private String objectName;
    private String address;
    private String layoutType;
    private Integer roomSize;
    private Integer age;
    private Long pcId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ObjectDao myDao;

    private PreviewConfirm previewConfirm;
    private Long previewConfirm__resolvedKey;

    private List<ObjectImage> objectImageList;

    public Object() {
    }

    public Object(Long id) {
        this.id = id;
    }

    public Object(Long id, String objectName, String address, String layoutType, Integer roomSize, Integer age, Long pcId) {
        this.id = id;
        this.objectName = objectName;
        this.address = address;
        this.layoutType = layoutType;
        this.roomSize = roomSize;
        this.age = age;
        this.pcId = pcId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getObjectDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectName() {
        return objectName;
    }

    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLayoutType() {
        return layoutType;
    }

    public void setLayoutType(String layoutType) {
        this.layoutType = layoutType;
    }

    public Integer getRoomSize() {
        return roomSize;
    }

    public void setRoomSize(Integer roomSize) {
        this.roomSize = roomSize;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Long getPcId() {
        return pcId;
    }

    public void setPcId(Long pcId) {
        this.pcId = pcId;
    }

    /** To-one relationship, resolved on first access. */
    public PreviewConfirm getPreviewConfirm() {
        Long __key = this.pcId;
        if (previewConfirm__resolvedKey == null || !previewConfirm__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PreviewConfirmDao targetDao = daoSession.getPreviewConfirmDao();
            PreviewConfirm previewConfirmNew = targetDao.load(__key);
            synchronized (this) {
                previewConfirm = previewConfirmNew;
            	previewConfirm__resolvedKey = __key;
            }
        }
        return previewConfirm;
    }

    public void setPreviewConfirm(PreviewConfirm previewConfirm) {
        synchronized (this) {
            this.previewConfirm = previewConfirm;
            pcId = previewConfirm == null ? null : previewConfirm.getId();
            previewConfirm__resolvedKey = pcId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ObjectImage> getObjectImageList() {
        if (objectImageList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ObjectImageDao targetDao = daoSession.getObjectImageDao();
            List<ObjectImage> objectImageListNew = targetDao._queryObject_ObjectImageList(id);
            synchronized (this) {
                if(objectImageList == null) {
                    objectImageList = objectImageListNew;
                }
            }
        }
        return objectImageList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetObjectImageList() {
        objectImageList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
