package com.example.wataru.greendao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.example.wataru.greendao.db.ObjectImage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table OBJECT_IMAGE.
*/
public class ObjectImageDao extends AbstractDao<ObjectImage, Long> {

    public static final String TABLENAME = "OBJECT_IMAGE";

    /**
     * Properties of entity ObjectImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectImage = new Property(1, byte[].class, "objectImage", false, "OBJECT_IMAGE");
        public final static Property SequenceNo = new Property(2, Integer.class, "sequenceNo", false, "SEQUENCE_NO");
        public final static Property ObjectId = new Property(3, Long.class, "objectId", false, "OBJECT_ID");
    };

    private DaoSession daoSession;

    private Query<ObjectImage> object_ObjectImageListQuery;

    public ObjectImageDao(DaoConfig config) {
        super(config);
    }
    
    public ObjectImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OBJECT_IMAGE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'OBJECT_IMAGE' BLOB," + // 1: objectImage
                "'SEQUENCE_NO' INTEGER," + // 2: sequenceNo
                "'OBJECT_ID' INTEGER);"); // 3: objectId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OBJECT_IMAGE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ObjectImage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        byte[] objectImage = entity.getObjectImage();
        if (objectImage != null) {
            stmt.bindBlob(2, objectImage);
        }
 
        Integer sequenceNo = entity.getSequenceNo();
        if (sequenceNo != null) {
            stmt.bindLong(3, sequenceNo);
        }
 
        Long objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindLong(4, objectId);
        }
    }

    @Override
    protected void attachEntity(ObjectImage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ObjectImage readEntity(Cursor cursor, int offset) {
        ObjectImage entity = new ObjectImage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getBlob(offset + 1), // objectImage
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // sequenceNo
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // objectId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ObjectImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectImage(cursor.isNull(offset + 1) ? null : cursor.getBlob(offset + 1));
        entity.setSequenceNo(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setObjectId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ObjectImage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ObjectImage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "objectImageList" to-many relationship of Object. */
    public List<ObjectImage> _queryObject_ObjectImageList(Long objectId) {
        synchronized (this) {
            if (object_ObjectImageListQuery == null) {
                QueryBuilder<ObjectImage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ObjectId.eq(null));
                object_ObjectImageListQuery = queryBuilder.build();
            }
        }
        Query<ObjectImage> query = object_ObjectImageListQuery.forCurrentThread();
        query.setParameter(0, objectId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getObjectDao().getAllColumns());
            builder.append(" FROM OBJECT_IMAGE T");
            builder.append(" LEFT JOIN OBJECT T0 ON T.'OBJECT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ObjectImage loadCurrentDeep(Cursor cursor, boolean lock) {
        ObjectImage entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Object object = loadCurrentOther(daoSession.getObjectDao(), cursor, offset);
        entity.setObject(object);

        return entity;    
    }

    public ObjectImage loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ObjectImage> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ObjectImage> list = new ArrayList<ObjectImage>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ObjectImage> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ObjectImage> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
